export const getExtensionMap: { [key: string]: string } = {
    '.js': 'JavaScript',
    '.js.': 'JavaScript',
    '.ts': 'TypeScript',
    '.py': 'Python',
    '.html': 'HTML',
    '.css': 'CSS',
    '.json': 'JSON',
    '.md': 'Markdown',
    '.xml': 'XML',
    '.yaml': 'YAML',
    '.yml': 'YAML',
    '.java': 'Java',
    '.c': 'C',
    '.cpp': 'C++',
    '.cs': 'C#',
    '.rb': 'Ruby',
    '.php': 'PHP',
    '.swift': 'Swift',
    '.kt': 'Kotlin',
    '.dart': 'Dart',
    '.sh': 'Shell',
    '.go': 'Go',
    '.rs': 'Rust',
    '.r': 'R',
    '.pl': 'Perl',
    '.lua': 'Lua',
    '.sql': 'SQL',
    '.scala': 'Scala',
    '.groovy': 'Groovy',
    '.erl': 'Erlang',
    '.ex': 'Elixir',
    '.exs': 'Elixir',
    '.hs': 'Haskell',
    '.jl': 'Julia',
    '.f90': 'Fortran',
    '.ml': 'OCaml',
    '.clj': 'Clojure',
    '.cljs': 'ClojureScript',
    '.coffee': 'CoffeeScript',
    '.elm': 'Elm',
    '.hx': 'Haxe',
    '.nim': 'Nim',
    '.cr': 'Crystal',
    '.zig': 'Zig',
    '.v': 'V',
    '.adb': 'Ada',
    '.ads': 'Ada',
    '.d': 'D',
    '.pas': 'Pascal',
    '.pp': 'Pascal',
    '.tpl': 'Template',
    '.m': 'MATLAB',
    '.fs': 'F#',
    '.fsi': 'F#',
    '.fsx': 'F#',
    '.fsscript': 'F#',
    '.asm': 'Assembly',
    '.s': 'Assembly',
    '.hxproj': 'Haxe',
    '.cmake': 'CMake',
    '.cmake.in': 'CMake',
    '.bat': 'Batch',
    '.cmd': 'Batch',
    '.vbs': 'VBScript',
    '.vb': 'Visual Basic',
    '.vba': 'VBA',
    '.vhd': 'VHDL',
    '.vhdl': 'VHDL',
    '.sv': 'SystemVerilog',
    '.svh': 'SystemVerilog',
    '.scss': 'SCSS',
    '.sass': 'Sass',
    '.less': 'LESS',
    '.styl': 'Stylus',
    '.tsx': 'TypeScript React',
    '.jsx': 'JavaScript React',
    '.vue': 'Vue',
    '.svelte': 'Svelte',
    '.graphql': 'GraphQL',
    '.gql': 'GraphQL',
    '.sol': 'Solidity',
    '.rbw': 'Ruby',
    '.thor': 'Ruby',
    '.rake': 'Ruby',
    '.pug': 'Pug',
    '.jade': 'Pug',
    '.haml': 'Haml',
    '.slim': 'Slim',
    '.ejs': 'EJS',
    '.hbs': 'Handlebars',
    '.mustache': 'Mustache',
    '.jinja': 'Jinja',
    '.jinja2': 'Jinja',
    '.twig': 'Twig',
    '.liquid': 'Liquid',
    '.mjml': 'MJML',
    '.dot': 'Graphviz',
    '.gv': 'Graphviz',
    '.uml': 'PlantUML',
    '.puml': 'PlantUML',
    '.wsdl': 'WSDL',
    '.xsd': 'XSD',
    '.xsl': 'XSLT',
    '.xslt': 'XSLT',
    '.jsp': 'Java Server Pages',
    '.asp': 'Active Server Pages',
    '.aspx': 'Active Server Pages',
    '.cshtml': 'Razor',
    '.vbhtml': 'Razor',
    '.eex': 'Elixir',
    '.leex': 'Elixir',

    '.hrl': 'Erlang',
    '.pro': 'Prolog',

    '.p': 'Prolog',
    '.tcl': 'Tcl',
    '.tk': 'Tcl',
    '.wsf': 'VBScript',
    '.wsh': 'VBScript',
    '.ahk': 'AutoHotkey',
    '.au3': 'AutoIt',
    '.ps1': 'PowerShell',
    '.psm1': 'PowerShell',
    '.psd1': 'PowerShell',
    '.bas': 'BASIC',
    '.cls': 'BASIC',
    '.frm': 'BASIC',
    '.ds': 'DataStage',
    '.dotnetproj': '.NET Project',
    '.csproj': '.NET Project',
    '.vbproj': '.NET Project',
    '.fsproj': '.NET Project',
    '.asproj': '.ASP Project',
    '.axd': 'ASP.NET',
    '.axml': 'Android XML',
    '.build': 'Build Script',
    '.config': 'Configuration File',
    '.conf': 'Configuration File',
    '.cfg': 'Configuration File',
    '.env': 'Environment File',
    '.ini': 'INI File',
    '.log': 'Log File',
    '.txt': 'Text File',
    '.readme': 'README File',
    '.changelog': 'Changelog File',
    '.license': 'License File',
    '.makefile': 'Makefile',
    '.gnumakefile': 'GNU Makefile',
    '.dockerfile': 'Dockerfile',
    '.dockerignore': 'Docker Ignore File',
    '.editorconfig': 'EditorConfig',
    '.eslintignore': 'ESLint Ignore File',
    '.eslintrc': 'ESLint Config',
    '.eslintcache': 'ESLint Cache',
    '.prettierrc': 'Prettier Config',
    '.prettierignore': 'Prettier Ignore File',
    '.babelrc': 'Babel Config',
    '.babelignore': 'Babel Ignore File',
    '.babelrc.js': 'Babel Config',
    '.babelrc.json': 'Babel Config',
    '.stylelintrc': 'Stylelint Config',
    '.stylelintignore': 'Stylelint Ignore File',
    '.markdownlint.json': 'Markdownlint Config',
    '.markdownlint.yaml': 'Markdownlint Config',
    '.markdownlint.yml': 'Markdownlint Config',
    '.npmignore': 'npm Ignore File',
    '.npmrc': 'npm Config',
    '.gitignore': 'Git Ignore File',
    '.gitattributes': 'Git Attributes File',
    '.gitmodules': 'Git Modules File',
    '.gitconfig': 'Git Config',
    '.svnignore': 'SVN Ignore File',
    '.hgignore': 'Mercurial Ignore File',
    '.jshintrc': 'JSHint Config',
    '.jshintignore': 'JSHint Ignore File',
    '.slugignore': 'Heroku Ignore File',
    '.cfignore': 'Cloud Foundry Ignore File',
    '.bzrignore': 'Bazaar Ignore File',
    '.boringignore': 'BoringSSL Ignore File',
    '.cvsignore': 'CVS Ignore File',
    '.rspec': 'RSpec Config',
    '.ru': 'Rackup Config',
    '.gemspec': 'RubyGems Spec',
    '.rvmrc': 'RVM Config',
    '.ruby-version': 'Ruby Version',
    '.ruby-gemset': 'Ruby Gemset',
    '.rubocop.yml': 'RuboCop Config',
    '.yardopts': 'YARD Config',
    '.php_cs': 'PHP CS Fixer Config',
    '.php_cs.dist': 'PHP CS Fixer Config',
    '.phpunit.xml': 'PHPUnit Config',
    '.phpunit.xml.dist': 'PHPUnit Config',
    '.phpmd.xml': 'PHPMD Config',
    '.phpmd.xml.dist': 'PHPMD Config',
    '.phpstan.neon': 'PHPStan Config',
    '.phpstan.neon.dist': 'PHPStan Config',
    '.behat.yml': 'Behat Config',
    '.atoum.xml': 'atoum Config',
    '.psalm.xml': 'Psalm Config',
    '.rector.yaml': 'Rector Config',
    '.rector.php': 'Rector Config',
};
